import fs from "fs";
import path from "path";
import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import dotenv from "dotenv";

// Load configs from .env into process.env
dotenv.config();

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// adjust the path to your dev vault as needed
const pluginId = JSON.parse(fs.readFileSync("./manifest.json", "utf8")).id;
const vaultPath = path.resolve(process.env.OBSIDIAN_VAULT_PATH, pluginId);

const copyToObsidian = {
	name: "copy-to-obsidian",
	setup(build) {
		build.onEnd(() => {
			if (prod) {
				return;
			}

			if (!fs.existsSync(vaultPath)) {
				fs.mkdirSync(vaultPath, { recursive: true });
			}

			fs.copyFileSync(
				"manifest.json",
				path.join(vaultPath, "manifest.json")
			);

			if (fs.existsSync("src/styles.css")) {
				fs.copyFileSync(
					"src/styles.css",
					path.join(vaultPath, "styles.css")
				);
			}

			console.log(
				`[${new Date().toLocaleTimeString()}] Build finished and files copied to obsidian.`
			);
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: prod ? "main.js" : path.join(vaultPath, "main.js"),
	plugins: [copyToObsidian],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
